%YAML:1.0

# akaze61 parameters

# Feature Extractor 
FeatureExtractor.numOctaves: 8
FeatureExtractor.scaleFactor: 1.1892 # 2^0.25
FeatureExtractor.detectionTh: 0.0005

# Feature Matcher 
FeatureMatcher.TH_HIGH: 100
FeatureMatcher.TH_LOW: 50
FeatureMatcher.descDistTh_high_reloc: 100
FeatureMatcher.descDistTh_low_reloc: 64
