%YAML:1.0

# akaze61 parameters

# Feature Extractor 
FeatureExtractor.nOctaves: 8
FeatureExtractor.scaleFactor: 1.1892 # 2^0.25
FeatureExtractor.detectTh: 0.00005
FeatureExtractor.maxNumFeatures: 1000

# Feature Matcher 
FeatureMatcher.TH_HIGH: 100
FeatureMatcher.TH_LOW: 50
FeatureMatcher.descDistTh_high_reloc: 100
FeatureMatcher.descDistTh_low_reloc: 64
