%YAML:1.0

# brisk48 parameters

# Feature Extractor 
FeatureExtractor.nOctaves: 8
FeatureExtractor.scaleFactor: 1.5
FeatureExtractor.detectTh: 17.0
FeatureExtractor.maxNumFeatures: 2000

# Feature Matcher 
FeatureMatcher.TH_HIGH: 120.0
FeatureMatcher.TH_LOW: 60.0
FeatureMatcher.descDistTh_high_reloc: 100
FeatureMatcher.descDistTh_low_reloc: 64
