%YAML:1.0

# kaze64 parameters

# Feature Extractor 
FeatureExtractor.nOctaves: 8
FeatureExtractor.scaleFactor: 1.1892 # 2^0.25
FeatureExtractor.detectTh: 0.0005
FeatureExtractor.maxNumFeatures: 2000

# Feature Matcher 
FeatureMatcher.matchingTh: 0.1

# Feature Matcher 
FeatureMatcher.TH_HIGH: 0.15
FeatureMatcher.TH_LOW: 0.1
FeatureMatcher.descDistTh_high_reloc: 0.15
FeatureMatcher.descDistTh_low_reloc: 0.1
